### ISSUE TITLE
Crashing on loading game

### ISSUE THREAD

**Issue by tkapis** [KozGit/DOOM-3-BFG-VR#109] opened 2017-03-05 21:56 UTC
I saved at the top of the stairs by the exit of Mars Underground and after the marine talking to me I saved again. The 1st save still works but when loading the 2nd one, the game crashes. In fact any save from then on crashes if I try to load it.

**Comment by CarlKenner** [comment] 2017-03-05 23:10
This is a duplicate of issue #103 crash when loading savegame.

**Comment by KozGit** [comment] 2017-03-13 05:21
Closing issue,  crashing from loading saves from the same version has been addressed per above,

**Closed by KozGit** 2017-03-13 05:21 UTC
