### ISSUE TITLE
Need to hold vive right grip button for hands to track

### ISSUE THREAD

**Issue by TheRealViper5** [KozGit/DOOM-3-BFG-VR#141] opened 2017-03-18 17:54 UTC
Hi,
When i enter the game (no other mods), my hands are seen motionless below and in front of me, to get them to track with the controllers i need to hold the right vive grip button, or have my thumb on the right touch pad or triggers. Is this normal? Using latest release alpha021

**Comment by KozGit** [comment] 2017-03-19 01:08
No, if you're in the game, the hands should track movement at all times. ( as long as the controllers are reporting valid tracking info.)

I'm not sure what would be causing this - try deleting your config ( located in %UserProfile%\Saved Games\id Software\DOOM 3 BFG\Fully Possessed ).  If you don't have any save games you want to keep, you can just delete that whole directory.

Restarting the game without the config will create a new default one, let me know if that helps.

**Comment by CarlKenner** [comment] 2017-03-19 04:04
That's caused by your gamepad or virtual gamepad. Either unplug it, make sure the triggers and analog sticks aren't being pressed, or set this console variable:

`vr_autoSwitchControllers 0`

**Comment by TheRealViper5** [comment] 2017-03-19 08:15
Thanks Carl, youre absolutely right, my xbox control was on and charging in the drawer, thanks a mill, you guys have done a fantastic job with this mod!

**Comment by KozGit** [comment] 2017-03-19 20:57
Glad it's working for you!  Closing issue as this appears to be resolved.

**Closed by KozGit** 2017-03-19 20:57 UTC
Labels: question
