### ISSUE TITLE
Weapon slot

### ISSUE THREAD

**Issue by tkapis** [KozGit/DOOM-3-BFG-VR#130] opened 2017-03-15 19:54 UTC
If you call up the menu or do a quick save, the weapon slot is cleared.

**Comment by CarlKenner** [comment] 2017-03-16 02:44
The menu does that because all GUIs do that. I don't know why quicksaves do though.

**Comment by tkapis** [comment] 2017-03-16 08:59
What do you mean by all GUIs do that? Quick save always opens the menu briefly and closes it again, so that is the reason I guess.

**Comment by CarlKenner** [comment] 2017-03-17 10:48
I was wrong sorry. I forgot I only implemented it on the PDA. I should do it on the other GUIs though, because I keep getting my finger stuck in a GUI while someone shoots at me (for example the crane game in Alpha Labs 3), and I want to reach into my holster and grab my gun back.

Because it was by design (at least the PDA part was). If you look down when you're using the PDA, you can see your gun hanging by your side, and you can grab your gun to put the PDA away. I knew that meant the current contents of the holster would be lost, but I figured that was consistent with the real world. You only have so many hands and places to put things.

But I guess people prefer video-game logic, so I'll see what I can do to fix it.

BTW, loading a quicksave (or any other save) also loses the contents of the holster, because I was trying not to change the format of the save files.

**Comment by tkapis** [comment] 2017-03-17 12:09
Oh now I understand, when you open a GUI it puts the present gun in the holster and when you close the GUI it retrieves it from the holster so now your holster is empty. That is realistic I agree but it means that you constantly have to set up the holster again which is pretty irritating.

Why does quick save open and close the menu?

**Comment by CarlKenner** [comment] 2017-03-17 12:25
I'm fixing this now.

You should have to use testSavegameEnumerate (or exit the program) between every save and it's loading.

**Comment by CarlKenner** [comment] 2017-03-17 13:22
This is fixed in the next version.

**Closed by CarlKenner** 2017-03-17 13:22 UTC
Labels: bug, enhancement
